#' Species taxonomy
#' 
#' An autogenerated dataset containing the species taxonomy.
#' 
#' \itemize{
#'   \item Genus: Genus 
#'   \item species: species
#'   \item Order: Order of species
#'   \item superfamily: superfamily of the species
#'   \item family: Family of species
#'   \item subfamily: Sub-family of species
#'   \item tribe: tribe of the species
#'   \item subgenus: subgenus of the species
#'   }
#' 
#' @docType data
#' @keywords datasets
#' @name taxonomy
#' @usage data(taxonomy)
#' @format A data frame with 8 columns and up to 20000 potential rows (for bees)
#' @aliases bee_taxonomy
"taxonomy"