#' Species taxonomy
#' 
#' An autogenerated dataset containing the species taxonomy.
#' 
#' \itemize{
#'   \item id: unique id of the table
#'   \item Genus: Genus 
#'   \item species: species
#'   \item Order: Order of species
#'   \item family: Family of species
#'   \item subfamily: Sub-family of species
#'   }
#' 
#' @docType data
#' @keywords datasets
#' @name taxonomy
#' @usage data(taxonomy)
#' @format A data frame with 6 columns and up to 20000 potential rows
"taxonomy"