---
title: 'traitbase.info: A generic open individual level trait database'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Authors:* Ignasi Bartomeus, Pedro J. Molina, Francisco P. Molina, ...

> "Trait data seems to be one of the most locked down bits of the data ecosystem" (Scott Chamberlain - ropensci)

#Abstract

Traitbase is a free and open database to share individual level species information. Ecological species characteristics like body size, diet or fecundity are of a huge importance for researchers trying to understand how species and ecosystems works. Despite as a collective we have generated immense data on ecological traits for different species, this data is scattered in different publications which often only report mean trait values or stored in private datasets. Traitbase aims to be a common place to share this information in a easy and fair way. The database is designed so it can be aesily extended to any organism, but initially you will find data only on pollinators. Each taxa has a curator that defines the traits and units acceptable for those taxa. Data is individual based, so each specimen can have different attributes and can be accessed raw, or summarized by species. Taxonomy is directly retrieved from ITIS. Only fully identified species are accepted. Data is automatically checked for correct taxonomy (synonyms and mispellings are corrected automatically), that trait values fall within sensible ranges and that geographical locations are credible. Data can be accessed via a wbepage, R package or API. The R package allows to download queried data, run automatic checks, run predefined functions to generate processed data and get the correct citation for the used data. To ensure long term storage with a citable DOI periodic data updates will be deposited in permanent repositories like dryad or Figshare.

Importance of traits, individual level.  
Lack of open, flexible curated database.
Traitbase: Infrastructure. 
Details: API, Rpackage, public release of data.
We provide an example (bees, but would be great to have also e.g. dung beetles).


#Introduction

Traits are ...

#Main characteritics

- Individual level
- Flexible
- Validated: Automate a local check on the data: Only fully identified species will be allowed.
- Open
- Curated
- Reproducible
- Long term preserved: Ensure long term permanent repository of the data in different realeases & Doi's. 
- API

# Ethics:  
Open data. Data can be used for research without restrictions, but appropiate credit is necesary. If you use data hosted at Traitbase, the level of credit you need to give to data contributors may be variable. At a minimum you should cite the original work containing the data used. All published dataset in Traitbase has a DOI or a list of contributors. If the data from one or various contributors plays a significant role in your analysis (either because is the primary data used or because its importance in the analysis), please consider contacting with the data contributor to discuss collaboration and/or co-authorship with them. In our experience, this kind of collaboration is a win-win situation, as only data collectors know the in and out of the data and can help tremendously in its use and interpretation
The Data Set has been released in the spirit of open scientific collaboration. Data Users are thus strongly encouraged to consider consultation, collaboration and/or co-authorship with the Data Set Creator.

#Technical specifications

Pedro, can you write down the technicalities. Database type, database structure, hosted at, unit tests implemented, 

The database structure has six datasets for each taxa group.

- Schema: This can be created for any group, and defines the traits and units that can be used. For now, there is only one schema, the one for bees (and maybe other pollintors). It's done in a way adding traits is easy and don't break the schema.  
- Species: Species taxonomy. This is autogenerated via `itis` and should not be edited by hand.  
- Traits: Specimen level data. Morphological, ecological, life history or physiological data measured on individuals from which to calculate mean and variance (if desired).   
- Observations: Some traits are inferred from observational data (e.g. flower specialization, range).   
- Datasets: Information stored for a set of observations like lat, long, ...  
- Contributors: Stores data to give apropiate credit.
- Photos: 


# Examples:

Including a bit of R code, and maybe a screenshot of the webpage.
a) sex ratios / body size relationship /world map.
b) discrepancy among datasets in categorical traits.

#Conclusing remarks

